language: node_js
node_js:
- '4'
- '6'
- node
dist: trusty
sudo: required
env:
  global:
  - BUILD_TIMEOUT=10000
  - SAUCE_USERNAME=PaulBGD
cache:
  directories:
  - "$HOME/.yarn-cache"
install: yarn
after_success:
- npm run codecov
jobs:
  include:
  - stage: benchmark
    script: node scripts/travis-bench.js
    node_js: '6'
addons:
  jwt:
    secure: paQL489vgNsfNpPW7cZw6lp0ludg05A3j1ZohzSnW/qMwdR4NEp2Dmpag+BTbB86dUK7uVEJCGQ0sASRpDXJjVuWfFLwUehuPwmREggy6O4TLpkRS3Evju2LdKZWF46bkJcf257R/CdfRD1ug1r83wQEzJCAje8mRyPDRucZy6oEYqy7Q+qs5HOfGDHP3giFnbiweqxjscP1et/+PA2wQmdnxTdIZTJ7qs0/vwD8bGlDz8qt/h9X4CAv2KgT0Mw1kYocC/pZExPgfHbbS7nYIWHtwl3I9SPgZ/Hd+cDu2F8AHVppeoJyFJ6N+lxlqfnPyShFzXrXD5phJwKjEfcQAb7VyWNYbX+kYKPd4RCoYP4RBaiSqR3NKz5lgJCRhPmaDxQD3aDkJ/Uc6uU++x+t6vdxEtPH8OgywoPJrAWtFmJppInR79KJstGe6K0/kwQ3eLWos+lDd3dxsQmMAOUqxmSREeY5trHSK/jb70VfafqMCEgvSVkyJNKUqqXivXg4NhxPKWCE62XoWtDxXq+0OzYZGMJx2pKjIrINo8Q8uFy+yjVyw6WUq7L/JStZU7mwotzUzLuoIisx/3W5qaw1atjd4e13M+NBx5G6f/RrGTWSma5iHmIjGgBmz1biPamNxGlHetfaonohRcYHGS8egeUHlWpyyQ20iSvtgiZBjAE=
