language: node_js
node_js:
- '4'
- '6'
- node
dist: trusty
sudo: required
env:
  global:
  - BUILD_TIMEOUT=10000
  - SAUCE_USERNAME=PaulBGD
addons:
  jwt:
    secure: DQK+GD8grif8WD3u+72h5ofO7pnyf0Jn8A2R4sEnBQtNeVRmzDtY/fOHDzUCVvUROb+sun+ERsXPx9IEqEJVp6rNNLGFhHjSfofSoKEP/uDY6jproetUPB4EMVBoS7gq9uwUa98/oOmAr0fWlkwxvueY+Ke8Sc2Cm7+Cos4AarFR+uW48o70d9AqzDzWlFSwAaNEuYPO25k26juOkh+J0IH++92il5aDBFzMhuZD28fElmRrds0Ne31X2gU9rlaVgd6Xk2tvZBdkizNKEIgLW4nGXsUe9WYXWhpvwfCEKGUdqaAvNC4LtU+YXtl4uWmiUz4Zz7y98Samw8cmj6voio8NIKjXOvmm4YGfwy7FmnRF1BTCJlFmJ56mGnDFaUvw2r2ju7DPhQEc07Y2M6m8j6iCJUV9/4dJry12LTTREK9ER3DNtvOUjN9Qq8194zKWWV3hCTkH917thTpG8+TWZ+TFffz/vAsOzLVESvLtMtcC5Y30GgyWdtI19lUfoL0j8+dcVFLmCbzOJ6+PdkydIKf3OD6EVL6pc8gY7o0cTH38r9qZbMozHHwOYUB98vE7jyu1JCWPBjmH8EwW5HgyZMyju71jb8Nq7uYdp3ggYIX7c/Xtpb+9oEnf5JXGQfJY1pujESeKPElhwfdNN5ktBkqTmUtnfqlB/0emdjFB2GM=
cache:
  directories:
  - "$HOME/.yarn-cache"
install: yarn
after_success:
- npm run codecov

jobs:
  include:
    - stage: benchmark
      script: node scripts/travis-bench.js
      node_js: '6'
