language: node_js
node_js:
  - "4"
  - "6"
  - "node"
dist: trusty
sudo: required
addons:
  firefox: "latest"
env:
  global:
    - BUILD_TIMEOUT=10000
cache:
  directories:
  - $HOME/.yarn-cache
before_install:
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome-stable_current_amd64.deb
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.14.0/geckodriver-v0.14.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.14.0-linux64.tar.gz -C geckodriver
  - wget https://chromedriver.storage.googleapis.com/2.29/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d chromedriver
  - export PATH=$PATH:$PWD/geckodriver:$PWD/chromedriver
  - "export DISPLAY=:99.0"
install: yarn
after_success: 
  - npm run codecov
  - npm run benchmark
